### ISSUE TITLE
Collaps on changed

### ISSUE THREAD

**Issue by spajdo** [Skylled/expansion_tile_card#10]
Hi. This is very nice plugin.
Is there an option to collapse card? I'm using it like color picker. I want expand card manually, then I select color from picker and I want collapse your card automatically. Is this possible?

**Comment by Skylled** [comment]
I tried to base this widget as closely as I could on Flutter's `ExpansionTile` to make sure it would work as a drop-in replacement. With that in mind, ExpansionTile does not have a method to be closed or opened programmatically, but it's clearly something others have wanted and made modifications for.

This SO answer is a great example: https://stackoverflow.com/a/48935106/955974

Would simply adding these `expand()`, `collapse()`, and `toggle()` methods be enough for your use case?

**Comment by sklorde** [comment]
@Skylled can you please add the methods?
Very nice widget! <3

**Comment by Skylled** [comment]
As shown in the SO answer, and now in the updated example app, you'll need to create a `GlobalKey<ExpansionTileCardState>` for each widget, and also set the `key` variable for each widget accordingly. From there, call that GlobalKey's `currentState.collapse()` method to collapse that card. Same for `expand()` and `toggleExpansion()`.

This will be available in the next version, which should hit Pub tonight or tomorrow.
