### ISSUE TITLE
Title shifts up and down on collapse/expand

### ISSUE THREAD

**Issue by sgehrman** [Skylled/expansion_tile_card#12]
I'm seeing the title move up and down a few pixels when expanding/collapsing.  The title should be stationary.

**Comment by Skylled** [comment]
It's going to be a little while before I roll a new version out with the fix, but in the meantime, this behavior can be overridden by setting `finalPadding` to something like `EdgeInsets.only(bottom: 6.0)`, or `EdgeInsets.zero` if you prefer.
