### ISSUE TITLE
Allow closing of tile programmatically

### ISSUE THREAD

**Issue by davidpanic** [Skylled/expansion_tile_card#15]
I just want to be able to close the expansion tile by calling some function.
That would enable the implementation of only allowing one expansion tile to be open at a time.

**Comment by Skylled** [comment]
Duplicate of #10.

Feel free to re-open with an explanation if the `currentState.collapse()` solution doesn't cover your use case.

**Comment by Skylled** [comment]
I'll make a note to include an example in the Readme and the demo app showing how to do this.
