### ISSUE TITLE
Re-check null safety migration

### ISSUE THREAD

**Issue by Skylled** [Skylled/expansion_tile_card#19]
Null safety is coming to Dart/Flutter, and we need to be ready. It may require a fair bit of work.

Current plan is to look to the library's upstream baseline of Flutter's ExpansionTile widget. Whatever solution is used there will likely work here as well.

https://dart.dev/null-safety/migration-guide

**Comment by sameeerkashyap** [comment]
@Skylled  is work on this in progress? If not, I'd like to help migrate the package.

**Comment by Skylled** [comment]
It would be my preference to perform this migration myself, to get experience with doing so and to make sure I fully understand how to write null safe code in the future.

However, if this package is perhaps preventing your app/package from migrating to null safety, I would be open to a pull request so as to unblock you as quickly as possible.

**Comment by sameeerkashyap** [comment]
@Skylled, yes I have a client app with multiple Categories and each of them using this widget to display subcategories, so it'd be great if I can do it, The PR will be up by the weekend. 

regarding what you mentioned, how about I only migrate the package, you could migrate the example that'd give you an idea about null safety.

Sound good?

**Comment by Skylled** [comment]
Closed as of 9bc4e03.

Will push 2.0.0 to Pub.dev shortly.

**Comment by Skylled** [comment]
Actually, going to leave this open as I've only done the migration tool, but a manual re-check could be beneficial.
