### ISSUE TITLE
Bug,_isExpanded is Wrong state after del item in List

### ISSUE THREAD

**Issue by fireknight** [Skylled/expansion_tile_card#9]
version:1.0.2+2

before I delete a item as ExpansionTileCard in my list,  the expansion title card is expanded,

then next item in the deleted item postion with expanded .
like this:
1 a item opend  --> delete
2 b item closed
3 c item closed

after
1 b item opend
2 c item closed

**Comment by Skylled** [comment]
You should be able to fix this in your code by giving each tile a unique `key`. What's happening is Flutter is copying the state from one to the other because it thinks the two widgets are the same.

**Comment by Skylled** [comment]
Quick example:
```dart
ListView.builder(itemBuilder: (context, index){
  return ExpansionTileCard(
    key: PageStorageKey('my-tile-$index'),
    title: Text('This is tile #$index'),
  );
})
```

**Comment by fireknight** [comment]
yes, i solved this problem by other way ,thank you!

**Comment by Skylled** [comment]
Would love to see your solution, if you're willing to share. Might be helpful for a future FAQ section in the README.

**Comment by talatkuyuk** [comment]
> yes, i solved this problem by other way ,thank you!
Bug,_isExpanded is Wrong state after del item in List

I have the same issue.
How did you solve the issue, can you share your solution..[fireknight]

key: PageStorageKey('my-tile-$index'),  didn't work for me.. [Skylled]

**Comment by fireknight** [comment]
> > yes, i solved this problem by other way ,thank you!
> > Bug,_isExpanded is Wrong state after del item in List
> 
> I have the same issue.
> How did you solve the issue, can you share your solution..[fireknight]
> 
> key: PageStorageKey('my-tile-$index'), didn't work for me.. [Skylled]

key:UniqueKey()

**Comment by fireknight** [comment]
> Would love to see your solution, if you're willing to share. Might be helpful for a future FAQ section in the README.

key:UniqueKey()

**Comment by Skylled** [comment]
Ah, I see the error in the code I gave. The string key you use definitely needs to be unique. By telling you to use `index`, I accidentally had you shifting the whole list's state upward on deletion. (Not to mention, it looks like my initial understanding of PageStorageKey was _completely wrong_.)

To expand on what fireknight is saying:
```dart
ListView.builder(itemBuilder: (context, index){
  return ExpansionTileCard(
    key: UniqueKey(),
    title: Text('This is tile #$index'),
  );
})
```

Keep in mind though, that UniqueKey may have some unintended side effects, as it will generate a new key when rebuilt, which would lead to losing your expansion state. Using one of the other kinds of keys like ValueKey or ObjectKey may be a better idea, as outlined here
https://medium.com/flutter/keys-what-are-they-good-for-13cb51742e7d

Additionally, many issues you may face with this library will also be found in the original ExpansionTile widget. Here's a relevant StackOverflow answer showing how to maintain isExpanded state after deletion:
https://stackoverflow.com/questions/54734905/flutter-how-to-maintain-isexpanded-status-of-expansiontiles-list-after-deleti
